"""Port interfaces for data access.

BudgetReader defines the read-only contract that DataContext satisfies.
Use for type-checking and test substitution (FakeReader).
"""

from typing import Protocol, runtime_checkable

from .models import Account, Category, Expense, Income


@runtime_checkable
class BudgetReader(Protocol):
    """Read-only budget data access contract."""

    def expenses(self) -> list[Expense]: ...
    def income(self) -> list[Income]: ...
    def categories(self) -> list[Category]: ...
    def accounts(self) -> list[Account]: ...
    def category_totals(self) -> dict[str, float]: ...
    def account_totals(self) -> dict[str, float]: ...
    def total_income(self) -> float: ...
    def total_expenses(self) -> float: ...
    def yearly_overview(self) -> dict: ...
    def expenses_by_category(self) -> dict[str, list[Expense]]: ...
    def category_usage(self) -> dict[str, int]: ...
    def account_usage(self) -> dict[str, int]: ...
